package mwg.wb.client.elasticsearch.dataquery;

public enum OrderType {
	NORMAL, DESCENDING, ASCENDING, PROMOTION_VALUE, PROMOTION_PERCENT, DISCOUNT_VALUE, FEATURE, FEATURE_PRICE_ASC,
	FEATURE_PRICE_DESC, PRICE, LARGEST, SMALLEST;
}
