package mwg.wb.model.search;

public class FaqSE {

	public int NewsID;
    public int CategoryID;
    public String Listcategoryid;
    public String ListTreeCategoryID;
    public String Title;
    public String Content;
    public String Keyword;
    public String Tags;
    public int IsActived;
    public int IsDeleted;
    public int Viewcounter;
    public int Likecounter;
    public int Dislikecount;
    public String Productidlist;
    public String Eventidlist;
    public String Hottopicidlist;
    public int Relateproductid;
    public String Createddate;
    public String Updateddate;
    public int Displayorder;
    public int Posttype;
    public int Userid;
    public int Storeid;
    public String Metatitle;
    public String Metadescription;
    public String Metakeyword;
    public int Labelid;
    public String Image;
    public String Url;
    public String Detailimage;
    public int IsCommentallow;
    public int IsGallery;
    public int IsVideo;
    public String Extenallink;
    public int IsFeature;
    public String IpCreated;
    public int IsSticked;
    public String Createduser;
    public String Listcategoryname;
    public int IsDraft;
    public int Siteid;
    public String Videolink;
    public String Topicidlist;
    public String Topicnamelist;
    public String Activeddate;
    public String Activeduser;
    public String Thumbnailimage;
    public String Shortdescription;
    public String Amountcomment;
}
